In [1]:
import cv2


cap = cv2.VideoCapture(0)
status , photo = cap.read()

In [2]:
cv2.imwrite('parv.png',photo)

True

In [5]:
cap.release()

In [66]:
cv2.imshow('parv photo',photo[100:300 , 250:400])
cv2.waitKey()
cv2.destroyAllWindows()


In [9]:
type(photo)

numpy.ndarray

In [10]:
import numpy as np

In [16]:
a = np.array([[1,11],
              [2,22],
              [3,33],])
a.shape

(3, 2)

In [17]:
photo.shape

(480, 640, 3)

In [18]:
photo

array([[[110, 101, 101],
        [111, 102, 102],
        [112, 103, 103],
        ...,
        [255, 236, 203],
        [253, 241, 205],
        [254, 245, 208]],

       [[111, 102, 102],
        [111, 102, 102],
        [111, 102, 102],
        ...,
        [255, 239, 206],
        [255, 243, 207],
        [255, 247, 210]],

       [[112, 103, 103],
        [112, 103, 103],
        [111, 102, 102],
        ...,
        [255, 241, 204],
        [255, 247, 207],
        [255, 251, 209]],

       ...,

       [[ 85,  87,  71],
        [ 85,  87,  70],
        [ 87,  89,  69],
        ...,
        [ 39,  32,  26],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 77,  82,  76],
        [ 78,  83,  75],
        [ 80,  83,  73],
        ...,
        [ 38,  31,  25],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 81,  86,  80],
        [ 82,  87,  79],
        [ 84,  87,  77],
        ...,
        [ 38,  31,  25],
        [ 36,  29,  23],
        [ 36,  29,  23]]

In [27]:
photo[0][0] = [0,0,0]

In [28]:
photo[20] = [0,255,0]

In [29]:
photo


array([[[  0,   0,   0],
        [111, 102, 102],
        [112, 103, 103],
        ...,
        [255, 236, 203],
        [253, 241, 205],
        [254, 245, 208]],

       [[111, 102, 102],
        [111, 102, 102],
        [111, 102, 102],
        ...,
        [255, 239, 206],
        [255, 243, 207],
        [255, 247, 210]],

       [[112, 103, 103],
        [112, 103, 103],
        [111, 102, 102],
        ...,
        [255, 241, 204],
        [255, 247, 207],
        [255, 251, 209]],

       ...,

       [[ 85,  87,  71],
        [ 85,  87,  70],
        [ 87,  89,  69],
        ...,
        [ 39,  32,  26],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 77,  82,  76],
        [ 78,  83,  75],
        [ 80,  83,  73],
        ...,
        [ 38,  31,  25],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 81,  86,  80],
        [ 82,  87,  79],
        [ 84,  87,  77],
        ...,
        [ 38,  31,  25],
        [ 36,  29,  23],
        [ 36,  29,  23]]

In [42]:
a[2][0] += 20 
a

array([[ 1, 11],
       [ 2, 22],
       [43, 33]])

In [43]:
a += 100
a

array([[101, 111],
       [102, 122],
       [143, 133]])

In [ ]:
photo[100:300 , 250:400]

task1 - Ek coustom photo  bnani h 

task2 - change face with someone

task3 - make your own face

task4 - get the sunglasses and append it to  your face

task5 - remove all the green and blue color and show red color 
