In [11]:
import cv2


cap = cv2.VideoCapture(0)
status , photo = cap.read()

In [12]:
cv2.imshow('photo1',photo)
cv2.waitKey()
cv2.destroyAllWindows()


In [ ]:
cap.release()

In [9]:
type(photo)

numpy.ndarray

In [10]:
import numpy as np

In [16]:
a = np.array([[1,11],
              [2,22],
              [3,33],])
a.shape

(3, 2)

In [17]:
photo.shape

(480, 640, 3)

In [18]:
photo

array([[[110, 101, 101],
        [111, 102, 102],
        [112, 103, 103],
        ...,
        [255, 236, 203],
        [253, 241, 205],
        [254, 245, 208]],

       [[111, 102, 102],
        [111, 102, 102],
        [111, 102, 102],
        ...,
        [255, 239, 206],
        [255, 243, 207],
        [255, 247, 210]],

       [[112, 103, 103],
        [112, 103, 103],
        [111, 102, 102],
        ...,
        [255, 241, 204],
        [255, 247, 207],
        [255, 251, 209]],

       ...,

       [[ 85,  87,  71],
        [ 85,  87,  70],
        [ 87,  89,  69],
        ...,
        [ 39,  32,  26],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 77,  82,  76],
        [ 78,  83,  75],
        [ 80,  83,  73],
        ...,
        [ 38,  31,  25],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 81,  86,  80],
        [ 82,  87,  79],
        [ 84,  87,  77],
        ...,
        [ 38,  31,  25],
        [ 36,  29,  23],
        [ 36,  29,  23]]

In [27]:
photo[0][0] = [0,0,0]

In [28]:
photo[20] = [0,255,0]

In [29]:
photo


array([[[  0,   0,   0],
        [111, 102, 102],
        [112, 103, 103],
        ...,
        [255, 236, 203],
        [253, 241, 205],
        [254, 245, 208]],

       [[111, 102, 102],
        [111, 102, 102],
        [111, 102, 102],
        ...,
        [255, 239, 206],
        [255, 243, 207],
        [255, 247, 210]],

       [[112, 103, 103],
        [112, 103, 103],
        [111, 102, 102],
        ...,
        [255, 241, 204],
        [255, 247, 207],
        [255, 251, 209]],

       ...,

       [[ 85,  87,  71],
        [ 85,  87,  70],
        [ 87,  89,  69],
        ...,
        [ 39,  32,  26],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 77,  82,  76],
        [ 78,  83,  75],
        [ 80,  83,  73],
        ...,
        [ 38,  31,  25],
        [ 37,  30,  24],
        [ 36,  29,  23]],

       [[ 81,  86,  80],
        [ 82,  87,  79],
        [ 84,  87,  77],
        ...,
        [ 38,  31,  25],
        [ 36,  29,  23],
        [ 36,  29,  23]]

In [42]:
a[2][0] += 20 
a

array([[ 1, 11],
       [ 2, 22],
       [43, 33]])

In [43]:
a += 100
a

array([[101, 111],
       [102, 122],
       [143, 133]])

In [13]:
photo[100:300 , 250:400]

array([[[ 67,  70,  71],
        [ 66,  69,  70],
        [ 66,  69,  70],
        ...,
        [ 66,  66,  69],
        [ 70,  70,  73],
        [ 73,  74,  81]],

       [[ 68,  71,  72],
        [ 67,  70,  71],
        [ 66,  69,  70],
        ...,
        [ 67,  67,  70],
        [ 71,  71,  74],
        [ 74,  75,  82]],

       [[ 71,  72,  73],
        [ 70,  71,  72],
        [ 68,  69,  70],
        ...,
        [ 64,  66,  74],
        [ 69,  69,  78],
        [ 73,  75,  83]],

       ...,

       [[109, 109, 105],
        [106, 107, 101],
        [105, 106,  99],
        ...,
        [ 60,  54,  62],
        [ 59,  52,  60],
        [ 55,  50,  58]],

       [[105, 105, 101],
        [103, 104,  98],
        [102, 104,  95],
        ...,
        [ 55,  54,  61],
        [ 53,  52,  59],
        [ 50,  50,  57]],

       [[ 98,  98,  94],
        [ 96,  97,  91],
        [ 95,  97,  88],
        ...,
        [ 55,  54,  61],
        [ 52,  51,  58],
        [ 49,  49,  56]]

task1 - Ek coustom photo  bnani h 

task2 - change face with someone

task3 - make your own face

task4 - get the sunglasses and append it to  your face

task5 - remove all the green and blue color and show red color 


In [1]:
import cv2
cap = cv2.VideoCapture(0)

In [12]:

while True: 

    status, photo = cap.read()

    cv2.imshow('pa', photo)

    
    if cv2.waitKey(100) ==13:
        break
cv2.destroyAllWindows()

In [17]:
cap.release()

ek coustom photo

In [2]:
import cv2
cap = cv2.VideoCapture(0)

In [11]:
status, photo = cap.read()

cv2.imshow('pa', photo [250:])
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [18]:
cv2.imwrite('image.png',photo)


True

In [21]:
photo * 0


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [22]:
cv2.imwrite('image.png',photo)

True